### ISSUE TITLE
can't get screenshot with default options

### ISSUE THREAD

**Issue by x0day** [webrecorder/simplechrome#25]
thanks for the project, because pyppeteer has not updated long time.

```
screenshot = await page.screenshot()
```
https://github.com/webrecorder/simplechrome/blob/fe1e372930704a11edf5f50b861a904152cb9681/simplechrome/page.py#L1124

raise `"options.clip and options.fullPage are exclusive"`,

why I need to set clip and fullPage all the time?

**Comment by N0taN3rd** [comment]
All though we have made significant changes to the core "puppeteer" API we try, when possible, to maintain its behavior.
Which, is in this case, is to require a you to supply either a clip or fullPage=True. 
 
https://github.com/GoogleChrome/puppeteer/blob/13f73b5b3a279f18313630e0f58c3c17fb0cef66/lib/Page.js#L830

**Comment by N0taN3rd** [comment]
tho I just noticed our example needs some updating

**Comment by x0day** [comment]
```
await page.screenshot({'fullPage': True, 'path': '1.jpeg'})
```
also doesn't work.

**Comment by x0day** [comment]
because default clip is None, so first condition is True, them error raises.

**Comment by N0taN3rd** [comment]
@x0day thanks for pointing this out

Below should work now

```python3
import asyncio
import aiofiles
import uvloop

from simplechrome import launch

uvloop.install()


async def test():
    loop = asyncio.get_event_loop()
    chrome = await launch(loop=loop)
    page = await chrome.newPage()
    await page.goto("http://example.com")
    scbuff = await page.screenshot()
    async with aiofiles.open("1.png", "wb") as out:
        await out.write(scbuff)
    await page.close()
    await chrome.close()


if __name__ == "__main__":
    asyncio.run(test())
```
