### ISSUE TITLE
please use --remote-debugging-port=0

### ISSUE THREAD

**Issue by x0day** [webrecorder/simplechrome#26]
Launcher will launch a chrome process at the port 9222 by default, so I can't start multi chrome browser at the same time if I didn't target the available port for it.

but in puppeteer, it will use  --remote-debugging-port=0 by default and find the ws port from stdout.

https://github.com/GoogleChrome/puppeteer/blob/master/lib/Launcher.js#L359

**Comment by N0taN3rd** [comment]
You can supply the port to be used as a launcher argument
https://github.com/webrecorder/simplechrome/blob/fe1e372930704a11edf5f50b861a904152cb9681/simplechrome/launcher.py#L199

**Comment by N0taN3rd** [comment]
does supplying the port fix your use case

**Comment by N0taN3rd** [comment]
@x0day the default port is 0 and the ws url is gotten from chromes `stderr`

**Comment by x0day** [comment]
nice! thank you!
